[book]
src = "src"
title = "Aloe II"

[output.html]
no-section-label = true
additional-js = ["solidity.min.js"]
additional-css = ["book.css"]
git-repository-url = "https://github.com/aloelabs/aloe-ii"
mathjax-support = true
default-theme = "ayu"

[output.html.fold]
enable = true
