name: slither

run-name: Slither Analysis

on:
  pull_request:
  push:
    branches:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: run-slither
        with:
          target: 'core/'
          fail-on: none
          slither-args: --config-file core/slither.config.json
          sarif: slither.results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.run-slither.outputs.sarif }}
