name: update-oracle

run-name: Poking the volatility oracle

on:
  schedule:
  - cron: '30 0,1,6,7,12,13,18,19 * * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: 'forge build'
  run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          forge script script/UpdateOracle.s.sol:UpdateOracleScript --fork-url ${{ RPC_URL_OPTIMISM }} --broadcast
